### ISSUE TITLE
startRecord API with "customized_path"

### ISSUE THREAD

**Issue by lenhatvu** [xiongziliang/ZLMediaKit#279]
I am trying start record API with "customized_path" param but the video file still locate in default folder. 
How to fix it ?

**Comment by xiongziliang** [comment]
You can refer to this issue: https://github.com/xiongziliang/zlmedia kit/issues/213

**Comment by lenhatvu** [comment]
Yes,

I am using your latest code with API: "/startRecord?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&type=1&vhost=__defaultVhost__&app=proxy&stream=cam1&wait_for_record=1&continue_record=1&**customized_path=cam1_rec**" but the video file still under "www/record/" folder

**Comment by xiongziliang** [comment]
The customized_path is a relative path in record root path.
Absolute path cannot be specified due to security considerations.

**Comment by lenhatvu** [comment]
Yes,

my path is "customized_path=cam1_rec". If correct, video file must under "www/record/cam1_rec" folder ?

**Comment by xiongziliang** [comment]
It should be, you can test it.

**Comment by lenhatvu** [comment]
customized_path still not affect.
Is "auto path = Recorder::getRecordPath(type, vhost, app, stream_id);" lack customized_path param ?
![customize path param](https://user-images.githubusercontent.com/59004953/80368374-d6f49500-88b6-11ea-817e-08a087061060.jpg)

**Comment by xiongziliang** [comment]
Sorry, the problem you mentioned is a bug. It has been fixed now， Thank you!

**Comment by lenhatvu** [comment]
Seem still not enough;
I am manual set customize path as image bellow and it's work;
![record path](https://user-images.githubusercontent.com/59004953/80456766-5dad7e80-8958-11ea-90d3-54d3c494b8d2.jpg)

**Comment by xiongziliang** [comment]
If you do not use [restful api](https://github.com/xiongziliang/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#20indexapistartrecord) to start a recording  , ZLMediaKit may start record by [conf](https://github.com/xiongziliang/ZLMediaKit/blob/master/conf/config.ini#L44) or [http hook](https://github.com/xiongziliang/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-HOOK-API#7on_publish).


And the default record path will ignore the "customize path".

**Comment by xiongziliang** [comment]
Sorry ,you're right,  i fixed this bug just now.

**Comment by lenhatvu** [comment]
Thanks!
Now it's work great
